version: '3'
services:
  order-service:
    image: open-telemetry-order:0.0.6-SNAPSHOT
    environment:
      OTEL_SERVICE_NAME: "order-service"
      OTEL_TRACES_EXPORTER: "jaeger,zipkin"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
    ports:
    - "8080:8080"
    depends_on:
    - postgres
    - jaeger-all-in-one
    - zipkin-all-in-one

  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.74.0
    environment:
    - COLLECTOR_OTLP_ENABLED=true
    restart: always
    ports:
    - "16686:16686"
    - "14250"

  zipkin-all-in-one:
    container_name: zipkin
    image: openzipkin/zipkin:3.5.1
    restart: always
    ports:
    - "9411:9411"

  postgres:
    container_name: postgres
    image: postgres:14.11
    restart: always
    environment:
      POSTGRES_DB: opentelemetry
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"